package frc.robot.subsystems;

import com.ctre.phoenix6.swerve.SwerveModule.DriveRequestType;
import com.ctre.phoenix6.swerve.SwerveRequest;
import com.ctre.phoenix6.swerve.SwerveRequest.ForwardPerspectiveValue;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import frc.robot.Constants.AimConstants;
import frc.robot.Constants.RoutineConstants;
import frc.robot.generated.TunerConstants;

/**
 * Everything this project adds to the swerve drivetrain.
 *
 * WHY A SUBCLASS: CommandSwerveDrivetrain and TunerConstants are generated by
 * the Phoenix Tuner X Swerve Project Generator, and hand edits there are lost
 * whenever the swerve config is regenerated. This class lives outside that
 * blast radius. If a regeneration changes a constructor signature, this file
 * stops compiling - loud, immediate, and far better than silently losing code.
 *
 * NOTE: because this builds itself from TunerConstants' public constants rather
 * than calling TunerConstants.createDrivetrain(), any future change to what
 * that factory passes (odometry frequency, std dev matrices) will NOT reach
 * here. Diff it after each regeneration.
 */
public class VisionSwerveDrivetrain extends CommandSwerveDrivetrain {

  /**
   * Aiming request. Zero deadbands and BlueAlliance perspective are NOT
   * stylistic choices:
   *
   * - Deadband: the teleop request uses a 10% deadband, which is right for a
   *   human on sticks and fatal for a control loop's output - it silently
   *   zeroes every correction below 10%, which is exactly the final-approach
   *   regime where the robot is converging.
   *
   * - ForwardPerspective: the default is OperatorPerspective, which rotates
   *   the target direction by the alliance perspective. All targeting math
   *   here is in the raw odometry frame, so that rotation would silently
   *   mirror the geometry - the same failure shape as a flipped heading sign,
   *   and just as invisible in a squared-up static test.
   */
  private final SwerveRequest.FieldCentricFacingAngle m_aimRequest =
      new SwerveRequest.FieldCentricFacingAngle()
          .withDeadband(0.0)
          .withRotationalDeadband(0.0)
          .withForwardPerspective(ForwardPerspectiveValue.BlueAlliance)
          .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

  private final SwerveRequest.FieldCentric m_fieldRelativeRequest =
      new SwerveRequest.FieldCentric()
          .withDeadband(0.0)
          .withRotationalDeadband(0.0)
          .withForwardPerspective(ForwardPerspectiveValue.BlueAlliance)
          .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

  /**
   * Same shape as m_aimRequest, but its own instance with its own rotation cap.
   *
   * A SEPARATE object on purpose. The drivebase verification routines want to
   * turn far faster than aiming does - kMaxAimRateRadPerSec is held low because
   * turn rate times camera latency is aiming error, and the routines involve no
   * camera at all. Mutating m_aimRequest's cap instead would silently leave the
   * faster rate in place for the next aim, which is exactly the kind of shared
   * mutable state that produces a bug nobody can reproduce.
   */
  private final SwerveRequest.FieldCentricFacingAngle m_routineRequest =
      new SwerveRequest.FieldCentricFacingAngle()
          .withDeadband(0.0)
          .withRotationalDeadband(0.0)
          .withForwardPerspective(ForwardPerspectiveValue.BlueAlliance)
          .withDriveRequestType(DriveRequestType.OpenLoopVoltage);

  private final SwerveRequest.Idle m_idleRequest = new SwerveRequest.Idle();

  public VisionSwerveDrivetrain() {
    super(
        TunerConstants.DrivetrainConstants,
        TunerConstants.FrontLeft,
        TunerConstants.FrontRight,
        TunerConstants.BackLeft,
        TunerConstants.BackRight);

    // The built-in heading controller operates on radians and outputs rad/s.
    // Continuous input is already enabled by FieldCentricFacingAngle's
    // constructor, so heading errors always take the short way round.
    m_aimRequest.HeadingController.setP(AimConstants.kHeadingP);
    m_aimRequest.HeadingController.setI(AimConstants.kHeadingI);
    m_aimRequest.HeadingController.setD(AimConstants.kHeadingD);
    m_aimRequest.MaxAbsRotationalRate = AimConstants.kMaxAimRateRadPerSec;

    // Same gains, faster rotation cap - see m_routineRequest's comment.
    m_routineRequest.HeadingController.setP(AimConstants.kHeadingP);
    m_routineRequest.HeadingController.setI(AimConstants.kHeadingI);
    m_routineRequest.HeadingController.setD(AimConstants.kHeadingD);
    m_routineRequest.MaxAbsRotationalRate = RoutineConstants.kMaxTurnRateRadPerSec;
  }

  /** The fused field pose: odometry plus any vision measurements added. */
  public Pose2d getRobotPose() {
    return getState().Pose;
  }

  /**
   * Chassis yaw rate in degrees per second, from the drivetrain's own state.
   *
   * Used by the settle check: "within tolerance" and "finished" are not the
   * same condition, and cutting the motors while the robot is still rotating
   * lets momentum carry it past the target.
   */
  public double getYawRateDegPerSec() {
    return Math.toDegrees(getState().Speeds.omegaRadiansPerSecond);
  }

  /**
   * Chassis translational speed magnitude in m/s, from the drivetrain's own
   * state. Used alongside yaw rate by the settle check: a command that
   * controls translation (DriveToTagCommand) must not declare arrival while
   * still coasting through the tolerance band, the same reasoning that
   * requires yaw rate to be near zero before declaring a turn settled.
   */
  public double getTranslationalSpeedMps() {
    var speeds = getState().Speeds;
    return Math.hypot(speeds.vxMetersPerSecond, speeds.vyMetersPerSecond);
  }

  /** Translate field-relative while the heading controller holds targetDirection. */
  public void driveFacingAngle(double vxMps, double vyMps, Rotation2d targetDirection) {
    setControl(m_aimRequest
        .withVelocityX(vxMps)
        .withVelocityY(vyMps)
        .withTargetDirection(targetDirection));
  }

  /** Open-loop field-relative drive with an explicit rotation rate. */
  public void driveFieldRelative(double vxMps, double vyMps, double omegaRadPerSec) {
    setControl(m_fieldRelativeRequest
        .withVelocityX(vxMps)
        .withVelocityY(vyMps)
        .withRotationalRate(omegaRadPerSec));
  }

  /**
   * Like {@link #driveFacingAngle}, but with the verification routines' faster
   * rotation cap instead of the aiming one. No camera is involved in those, so
   * the low aiming turn rate (which exists to bound turn-rate x latency error)
   * would only make a 90-degree corner take 3.6 seconds for no reason.
   */
  public void driveRoutineFacingAngle(double vxMps, double vyMps, Rotation2d targetDirection) {
    setControl(m_routineRequest
        .withVelocityX(vxMps)
        .withVelocityY(vyMps)
        .withTargetDirection(targetDirection));
  }

  /** Stop commanding motion. Named stopDrive() to avoid clashing with any base method. */
  public void stopDrive() {
    setControl(m_idleRequest);
  }
}
